version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
      - ./public:/var/www/html/public

    ports:
      - "8000:80"
    environment:
      - APP_NAME=Ecommerce
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:FBHyzZQCYx8wDD1uuv8/N9tBmgUOnozaQWizCaVVgJs=
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      - db

  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret

volumes:
  db_data:
